[workspace]

members = [
    "sn_cryptography",
    "sn_node",
    "sn_chain",
    "sn_store",
    "sn_proto",
    "sn_block",
    "sn_transaction",
    "sn_merkle",
    "sn_cli",
    "sn_mempool",
    "sn_server",
]
