[workspace]

members = [
    "vec_crypto",
    "vec_node",
    "vec_chain",
    "vec_storage",
    "vec_proto",
    "vec_utils",
    "vec_merkle",
    "vec_cli",
    "vec_mempool",
    "vec_errors",
    "vec_vm",
]
