[workspace]

members = [
    "vec_cryptography",
    "vec_node",
    "vec_chain",
    "vec_store",
    "vec_proto",
    "vec_block",
    "vec_transaction",
    "vec_merkle",
    "vec_cli",
    "vec_mempool",
    "vec_server",
    "vec_errors",
]
