[workspace]

members = [
    "vec_crypto",
    "vec_node",
    "vec_chain",
    "vec_storage",
    "vec_proto",
    "vec_block",
    "vec_transaction",
    "vec_merkle",
    "vec_cli",
    "vec_mempool",
    "vec_errors",
]
