[package]
name = "vec_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec_errors = { path = "../vec_errors", version = "0.1.0"}

wasmtime = "9.0.3"
sled = "0.34.7"