[package]
name = "vec_cryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


rand = "0.8.0"
sha3 = "0.10.6"
curve25519-dalek-ng = "4.1.1"
bs58 = "0.5.0"
digest = "0.10.7"